services:
  postgres:
    image: postgres:16
    container_name: chatapp-postgres
    environment:
      POSTGRES_DB: chatapp_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chatapp-network

  redis:
    image: redis:7.2
    container_name: chatapp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - chatapp-network
    command: redis-server --appendonly yes

networks:
  chatapp-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: