server:
  port: 8082

spring:
  application:
    name: messaging-service
  data:
    mongodb:
      uri: mongodb+srv://mrrdavidd:lrrDHlAcQHFC1dg6@hiep.segu1.mongodb.net/chatapp_messages
      auto-index-creation: true
      connection-pool:
        max-size: 100
        min-size: 10
      connect-timeout: 10000
      socket-timeout: 10000
      max-wait-time: 10000
      max-connection-idle-time: 300000
      max-connection-life-time: 3600000
      server-selection-timeout: 15000
      heartbeat-frequency: 10000
      local-threshold: 15
      retry-writes: true
      retry-reads: true
      ssl:
        enabled: true
        invalid-hostname-allowed: false
      write-concern: MAJORITY
      read-concern: MAJORITY
      read-preference: PRIMARY_PREFERRED

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2.0
    connection-timeout: 5000
    template:
      reply-timeout: 5000

  web:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      exposed-headers: "Authorization"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    com.chatapp: INFO
    org.springframework.web: INFO
    org.springframework.data.mongodb: INFO
    org.mongodb.driver: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/messaging-service.log
    max-size: 10MB
    max-history: 7

jwt:
  secret: ${JWT_SECRET:your_jwt_secret_key_here_make_it_long_and_secure_at_least_256_bits}
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
  health:
    mongodb:
      enabled: true
    rabbitmq:
      enabled: true

websocket:
  allowed-origins: ${WS_ALLOWED_ORIGINS:http://localhost:5173}
  endpoint: /ws
  destination-prefixes: /topic,/queue
  user-registry: /user
  heartbeat:
    incoming: 25000
    outgoing: 25000